In [170]:
import zipfile
with zipfile.ZipFile("../data/raw/processed/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw/processed")

In [171]:
import pandas as pd

In [172]:
s = pd.Series([10,30,30])
print (s)

0    10
1    30
2    30
dtype: int64

In [173]:
pd.DataFrame({})

Empty DataFrame
Columns: []
Index: []

In [174]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [175]:
data = {
    "customer": ["Anna", "David", "Liza"],
    "revenue": [100, 250, 180]
}

df = pd.DataFrame(data)
df

  customer  revenue
0     Anna      100
1    David      250
2     Liza      180

In [176]:
import pandas as pd

df_orders = pd.read_csv("../data/raw/processed/orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [177]:
df_orders.shape

(3421083, 7)

In [178]:
print (type(df_orders))
print (type ( df_orders.shape))

<class 'pandas.DataFrame'>
<class 'tuple'>

In [179]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [180]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [181]:
df_products = pd.read_csv("../data/raw/processed/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [182]:
df_products.shape

(49693, 5)

### Загрузка данных из csv файлов

### orders

In [183]:
import pandas as pd

df_orders = pd.read_csv('../data/raw/processed/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

### working with "orders"

In [184]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [185]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [186]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [187]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [188]:
df_orders["order_id"].nunique()

3421083

In [189]:
df_orders.shape

(3421083, 7)

In [190]:
df_orders.shape[0]

3421083

In [191]:
df_orders["order_id"]

0          2539329
1          2398795
2           473747
3          2254736
4           431534
            ...
3421078    2266710
3421079    1854736
3421080     626363
3421081    2977660
3421082     272231
Name: order_id, Length: 3421083, dtype: int64

In [192]:
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print("нет дубликатов")
else: 
    print ("есть дубликаты")

нет дубликатов

In [193]:
df_orders['order_id'].nunique()

3421083

In [194]:
df_orders["order_id"].nunique()

3421083

In [195]:
df_orders["user_id"].nunique()

206209

In [196]:
df_orders["order_id"].nunique()/df_orders["user_id"].nunique()

16.590367054784224

In [197]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [198]:
df_dow = df_orders['order_dow'].value_counts(ascending=False).reset_index()

In [199]:
df_dow.sort_values('order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

### index = false - сохраняет файл без индекса, то есть без дополнительного столбца с индексами строк. Это полезно, если вам не нужен индекс в сохраненном файле и вы хотите сохранить только данные.

In [200]:
df_dow.to_csv('../data/raw/processed/dow.csv', index = False)

### order_hour_of_day

In [201]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')

df_ohod

    order_hour_of_day   count
18                  0   22758
19                  1   12398
21                  2    7539
23                  3    5474
22                  4    5527
20                  5    9569
17                  6   30529
13                  7   91868
10                  8  178201
7                   9  257812
0                  10  288418
1                  11  284728
5                  12  272841
4                  13  277999
3                  14  283042
2                  15  283639
6                  16  272553
8                  17  228795
9                  18  182912
11                 19  140569
12                 20  104292
14                 21   78109
15                 22   61468
16                 23   40043

In [202]:
df_ohod.head(5)

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [203]:
df_ohod.to_csv('../data/raw/processed/ohod.csv')

In [204]:
df_ohod.to_excel('../data/raw/processed/ohod.xlsx', index = False)

In [205]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [206]:
needed_columns = ['days_since_prior_order', 'order_number','user_id']

In [207]:
df_first_orders = df_orders[needed_columns][df_orders['order_number'] == 1].reset_index()

In [208]:
df_first_orders = df_first_orders.drop(columns= 'index')

In [209]:
df_first_orders.head()

   days_since_prior_order  order_number  user_id
0                     NaN             1        1
1                     NaN             1        2
2                     NaN             1        3
3                     NaN             1        4
4                     NaN             1        5

In [210]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [211]:
df_orders_train.shape

(131209, 7)

### orders_products_train.csv

In [212]:

df_orders_products_train = pd.read_csv('../data/raw/processed/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

### products_csv

In [213]:
df_products = pd.read_csv("../data/raw/processed/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

### departments_t.csv

In [214]:
df_departments = pd.read_csv('../data/raw/processed/departments.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21'],
      dtype='str')
(1, 22)

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

### aisles.csv

In [215]:
df_aisles = pd.read_csv('../data/raw/processed/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [216]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [217]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [218]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [219]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [220]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
)

df_train_transactions_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.00,196,1,1
1,1187899,1,train,11,4,8,14.00,25133,2,1
2,1187899,1,train,11,4,8,14.00,38928,3,1
3,1187899,1,train,11,4,8,14.00,26405,4,1
4,1187899,1,train,11,4,8,14.00,39657,5,1

In [221]:
df_products_aisles =  pd.merge(df_products, df_aisles, on= "aisle_id", how = "left")

In [222]:
df_products_aisles

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation
...,...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.30,spirits
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.10,frozen vegan vegetarian
49690,49686,Artisan Baguette,112,3,7.80,bread
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.70,cat food care
49692,49688,Fresh Foaming Cleanser,73,11,13.50,facial care

In [223]:
df_departments

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [236]:
df_departments_t = df_departments.T 
df_departments_t.head()

                        0
department_id  department
1                  frozen
2                   other
3                  bakery
4                 produce

In [237]:
df_departments_t.reset_index(inplace=True)
df_departments_t.head()

           index           0
0  department_id  department
1              1      frozen
2              2       other
3              3      bakery
4              4     produce

In [240]:
new_header = df_departments_t.iloc[0]
new_header

index    department_id
0           department
Name: 0, dtype: str

In [251]:
df_departments_t_new = df_departments_t[1:]
df_departments_t_new

   index                0
1      1           frozen
2      2            other
3      3           bakery
4      4          produce
5      5          alcohol
6      6    international
7      7        beverages
8      8             pets
9      9  dry goods pasta
10    10             bulk
11    11    personal care
12    12     meat seafood
13    13           pantry
14    14        breakfast
15    15     canned goods
16    16       dairy eggs
17    17        household
18    18           babies
19    19           snacks
20    20             deli
21    21          missing

In [252]:
df_departments_t_new.columns = new_header

In [268]:
int(df_departments_t_new.shape[0])

21

In [269]:
df_departments_t_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 1 to 21
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     str
 1   department     21 non-null     str
dtypes: str(2)
memory usage: 468.0 bytes

In [290]:
df_departments_t_new = pd.read_csv('../data/processed/departments_t_new.csv')

In [291]:
df_departments_t_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [292]:
df_products_aisles

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation
...,...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.30,spirits
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.10,frozen vegan vegetarian
49690,49686,Artisan Baguette,112,3,7.80,bread
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.70,cat food care
49692,49688,Fresh Foaming Cleanser,73,11,13.50,facial care

In [293]:
df_products_aisles_department = pd.merge(df_products_aisles,df_departments_t_new, 
                                         on = 'department_id',
                                         how = 'left')

In [294]:
df_products_aisles_department

,product_id,product_name,aisle_id,department_id,prices,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation,pantry
...,...,...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.30,spirits,alcohol
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.10,frozen vegan vegetarian,frozen
49690,49686,Artisan Baguette,112,3,7.80,bread,bakery
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.70,cat food care,pets
49692,49688,Fresh Foaming Cleanser,73,11,13.50,facial care,personal care