In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
df_instacart = pd.read_parquet("../data/processed/instacart.parquet")
df_instacart.head()

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,beverages,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,snacks,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [4]:
def full_name(first_name,last_name):
    # logic
    full_name = first_name + " " + last_name
    return full_name

In [5]:
full_name("Hranush","Navoyan")

'Hranush Navoyan'

In [7]:
def age_segment(age:int):
    if age>=65:
        return "old"
    else:
        return "young"

In [8]:
age_segment(15)

'young'

In [20]:
def gross_salary(net_salary: int, tax:float = 0.2):
    gross = net_salary*(1+tax)

    return gross

In [21]:
gross_salary(50000)

60000.0

In [35]:
def сумма_покупки_со_скидкой(сумма:int, скидка:float = 0.5, active = True):
    if active:
        сумма_скидки = сумма*скидка

        return сумма_скидки

In [36]:
сумма_покупки_со_скидкой(500)

250.0

In [37]:
сумма_покупки_со_скидкой(500, скидка = 0.1)

50.0

In [10]:
df_instacart["Age"].head()

0    31
1    31
2    31
3    31
4    31
Name: Age, dtype: int64

In [38]:
def score_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Pass"
    else:
        return "Fail"

score_label(85)

'Good'

In [39]:
import pandas as pd

df_scores = pd.DataFrame({
    "student": ["Anna", "Ben", "Chris", "Diana", "Eva"],
    "score": [95, 78, 61, 43, 88]
})

df_scores

  student  score
0    Anna     95
1     Ben     78
2   Chris     61
3   Diana     43
4     Eva     88

In [40]:
df_scores["check"] = [i for i in df_scores["score"]]

In [41]:
df_scores

  student  score  check
0    Anna     95     95
1     Ben     78     78
2   Chris     61     61
3   Diana     43     43
4     Eva     88     88

In [43]:
df_scores["mark"] = [score_label(i) for i in df_scores["score"]]

In [44]:
df_scores

  student  score  check       mark
0    Anna     95     95  Excellent
1     Ben     78     78       Good
2   Chris     61     61       Pass
3   Diana     43     43       Fail
4     Eva     88     88       Good

In [45]:
df_scores["score"].apply(score_label)

0    Excellent
1         Good
2         Pass
3         Fail
4         Good
Name: score, dtype: str

In [47]:
df_scores['mark_apply'] = df_scores["score"].apply(score_label)

In [48]:
df_scores

  student  score  check       mark mark_apply
0    Anna     95     95  Excellent  Excellent
1     Ben     78     78       Good       Good
2   Chris     61     61       Pass       Pass
3   Diana     43     43       Fail       Fail
4     Eva     88     88       Good       Good

In [49]:
def classify_price(price, low=5, high=15):
    if price <= low:
        return "Low-range product"
    elif price <= high:
        return "Mid-range product"
    else:
        return "High-range product"

classify_price(9)

'Mid-range product'

In [50]:
classify_price(9, low=3, high=10)

'Mid-range product'

In [51]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [52]:
def age_group_label(age):
    if age < 30:
        return "Young"
    elif age < 60:
        return "Middle"
    else:
        return "Senior"

df_customers_dummy["age_group"] = df_customers_dummy["age"].apply(age_group_label)
df_customers_dummy

  customer  age  income age_group
0        A   22   18000     Young
1        B   35   42000    Middle
2        C   47   72000    Middle
3        D   63   95000    Senior
4        E   29   25000     Young

In [53]:
def income_band(income, low=30000, high=70000):
    if income < low:
        return "Low income"
    elif income < high:
        return "Middle income"
    else:
        return "High income"

df_customers_dummy["income_group"] = df_customers_dummy["income"].apply(income_band)
df_customers_dummy

  customer  age  income age_group   income_group
0        A   22   18000     Young     Low income
1        B   35   42000    Middle  Middle income
2        C   47   72000    Middle    High income
3        D   63   95000    Senior    High income
4        E   29   25000     Young     Low income

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt

In [ ]:
df_instacart = pd.read_parquet('../data/processed/instacart.parquet')

In [ ]:
df_instacart.head()

In [5]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [6]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [7]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#a34e31"]
)

fig.show()

In [8]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8"]
)

fig.show()

NameError: name 'region_product_sales' is not defined